/*
 * File: app/store/ArtistCategory.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyMusicBox.store.ArtistCategory', {
    extend: 'Ext.data.Store',

    requires: [
        'MyMusicBox.model.ArtistCategory'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                id: 0,
                text: '全部歌手'
            },
            {
                id: 1,
                text: '华语男歌手'
            },
            {
                id: 2,
                text: '华语女歌手'
            },
            {
                id: 3,
                text: '华语乐队组合'
            },
            {
                id: 4,
                text: '欧美男歌手'
            },
            {
                id: 5,
                text: '欧美女歌手'
            },
            {
                id: 6,
                text: '欧美乐队组合'
            },
            {
                id: 7,
                text: '日韩男歌手'
            },
            {
                id: 8,
                text: '日韩女歌手'
            },
            {
                id: 9,
                text: '日韩乐队组合'
            },
            {
                id: 10,
                text: '其他歌手'
            }
        ],
        model: 'MyMusicBox.model.ArtistCategory',
        storeId: 'ArtistCategory'
    }
});