/*
 * File: app/view/PlayView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyMusicBox.view.PlayView', {
    extend: 'Ext.Container',
    alias: 'widget.playview',

    requires: [
        'Ext.Img',
        'Ext.SegmentedButton',
        'Ext.Button',
        'Ext.field.Slider',
        'Ext.Audio'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                flex: 1,
                layout: 'hbox',
                items: [
                    {
                        xtype: 'image',
                        height: 200,
                        padding: '5 5 5 5',
                        width: 200,
                        src: 'resources/icons/disc.png'
                    },
                    {
                        xtype: 'container',
                        flex: 1,
                        layout: {
                            type: 'vbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'segmentedbutton',
                                allowDepress: true,
                                items: [
                                    {
                                        xtype: 'button',
                                        pressed: true,
                                        itemId: 'loopButton',
                                        ui: 'action',
                                        iconCls: 'shuffle'
                                    }
                                ]
                            },
                            {
                                xtype: 'component',
                                height: 40
                            },
                            {
                                xtype: 'segmentedbutton',
                                allowDepress: true,
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'mutedButton',
                                        ui: 'action',
                                        iconCls: 'volume'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'component',
                height: 40,
                html: '歌曲',
                itemId: 'songName'
            },
            {
                xtype: 'component',
                height: 40,
                html: '歌手',
                itemId: 'songArtist'
            },
            {
                xtype: 'container',
                height: 40,
                itemId: 'playButtons',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'prevButton',
                        ui: 'plain',
                        width: 80,
                        iconCls: 'rewind'
                    },
                    {
                        xtype: 'button',
                        itemId: 'playButton',
                        ui: 'plain',
                        width: 80,
                        iconCls: 'play'
                    },
                    {
                        xtype: 'button',
                        itemId: 'nextButton',
                        ui: 'plain',
                        width: 80,
                        iconCls: 'forward'
                    }
                ]
            },
            {
                xtype: 'sliderfield',
                height: 60
            },
            {
                xtype: 'audio',
                hidden: true
            }
        ]
    }

});