/*
 * File: app/model/Playlist.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyMusicBox.model.Playlist', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.identifier.Uuid'
    ],

    config: {
        identifier: {
            type: 'uuid'
        },
        fields: [
            {
                name: 'name'
            },
            {
                name: 'url'
            },
            {
                name: 'artist'
            },
            {
                name: 'artist_id',
                type: 'int'
            },
            {
                name: 'original_id',
                type: 'int'
            },
            {
                name: 'id',
                type: 'auto'
            }
        ]
    }
});