/*
 * File: app/controller/Play.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyMusicBox.controller.Play', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            audio: 'audio',
            playView: 'playview',
            songName: '#songName',
            songArtist: '#songArtist',
            playButton: 'playview #playButtons #playButton',
            playProgress: 'sliderfield'
        },

        control: {
            "playButton": {
                tap: 'onPlayButtonTap'
            },
            "audio": {
                timeupdate: 'onAudioTimeupdate'
            },
            "sliderfield": {
                dragstart: 'onDragStart',
                dragend: 'onDragEnd'
            }
        }
    },

    onPlayButtonTap: function(button, e, eOpts) {
        console.log('onPlayButtonTap');
        if (button.getIconCls()=='pause') {
            this.getAudio().pause();
            button.setIconCls('play');
        } else {
            this.getAudio().play();
            button.setIconCls('pause');
        }
    },

    onAudioTimeupdate: function(media, time, eOpts) {
        var me = this,
            playProgress = this.getPlayProgress(),
            duration = media.getDuration();

        if (duration > 0) {
            playProgress.setValue(time*100/duration);
        } else {
            playProgress.setValue(1);
        }

    },

    onDragStart: function(sliderfield, sl, thumb, value, e, eOpts) {
        var me = this,
            playButton = me.getPlayButton();

        if (playButton.getIconCls() == 'pause') {
            me.getAudio().pause();
        }
    },

    onDragEnd: function(sliderfield, sl, thumb, value, e, eOpts) {
        var me = this,
            audio = me.getAudio(),
            playButton =me.getPlayButton();

        audio.media.dom.currentTime = audio.getDuration()*value[0]/100;
        if (playButton.getIconCls() == 'pause') {
            audio.play();
        }
    },

    playASong: function(songRecord) {
        var me = this,
            a = this.getAudio();
        a.setUrl(songRecord.data.url);
        me.getSongName().setHtml(songRecord.data.name);
        me.getSongArtist().setHtml(songRecord.data.artist);
        me.getPlayButton().setIconCls('pause');
        a.play();
    }

});