/*
 * File: app/controller/Play.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyMusicBox.controller.Play', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            audio: 'audio',
            playView: 'playview',
            songName: '#songName',
            songArtist: '#songArtist',
            playButton: 'playview #playButtons #playButton'
        },

        control: {
            "playButton": {
                tap: 'onPlayButtonTap'
            }
        }
    },

    onPlayButtonTap: function(button, e, eOpts) {
        console.log('onPlayButtonTap');
        if(button.getIconCls()=='pause'){
            this.getAudio().pause();
            button.setIconCls('play');
        } else {
            this.getAudio().play();
            button.setIconCls('pause');
        }
    },

    playASong: function(songRecord) {
        var me = this,
            a = this.getAudio();
        a.setUrl(songRecord.data.url);
        me.getSongName().setHtml(songRecord.data.name);
        me.getSongArtist().setHtml(songRecord.data.artist);
        me.getPlayButton().setIconCls('pause');
        a.play();
    }

});